import tkinter as tk
import sqlite3
from tkinter import ttk
root = tk.Tk()
root.geometry('600x400')
root.title('Table Display')
root.configure(bg="#B775F5")
frame = tk.Frame(root, width=640, height=480)
frame.pack()
columns = ('#1', '#2', '#3', '#4', '#5')
treeview = ttk.Treeview(frame, columns=columns, show='headings')
treeview.heading('#1', text='ID')
treeview.heading('#2', text='Name')
treeview.heading('#3', text='Date')
treeview.heading('#4', text='Time')
treeview.heading('#5', text='Location')
conn = sqlite3.connect('faces.db')
c = conn.cursor()
data = c.execute('SELECT * FROM attendanceface')
for row in data:
    treeview.insert('', 'end', values=row)
treeview.column('#1', width=50, anchor='center')
treeview.column('#2', width=100, anchor='center')
treeview.column('#3', width=100, anchor='center')
treeview.column('#4', width=100, anchor='center')
treeview.column('#5', width=100, anchor='center')
treeview.pack(side='left')
scrollbar = ttk.Scrollbar(frame, orient='vertical', command=treeview.yview)
scrollbar.pack(side='right', fill='y')
treeview.configure(yscrollcommand=scrollbar.set)
root.mainloop()
